eureka:
  client:
    register-with-eureka: false
server:
  port: 8222
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: loan-order
          uri: http://localhost:8081
          predicates:
            - Path=/**
management:
  tracing:
    sampling:
      probability: 1.0