eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8081
spring:
  application:
    name: loan-order
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mts-loan-db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    enabled: true

schedule:
  fixedRate: PT02M

resilience4j:
  circuitbreaker:
    instances:
      loan-order:
        failure-rate-threshold: 30
        sliding-window-size: 3
        sliding-window-type: count-based
        wait-duration-in-open-state: 1m
        slow-call-duration-threshold: 1s
        permitted-number-of-calls-in-half-open-state: 1

management:
  tracing:
    sampling:
      probability: 1.0

